title: Student 2.0
description: "August 2023 to June 2024"
owner_name: Tanujsai Nimmagadda
github_username: Tanuj253
baseurl: "/student"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: pages-themes/chirpy@v6.1.0
plugins:
- jekyll-remote-theme
future: true